### ISSUE TITLE
Skill

### ISSUE THREAD

**Issue by Aymerix01** [ValTOrganization/Etapes#9]
J'ai trouvé une erreur dans le fichier Etape.uproject : 

![Capture d'écran 2024-04-08 145817](https://github.com/ValTOrganization/Etapes/assets/123820772/d577781a-87b4-4b19-b4ad-13c4c92382c6)

Il ne peut pas y avoir deux fois "Name"

**Comment by EneVyctis** [comment]
Tout d'abord merci pour le signalement, nous corrigerons cette erreur dans notre prochaine mise à jour!

Je n'ai cependant pas compris le lien entre l'erreur et le titre, le titre indique t'il un autre manque au projet ou puis-je clore l'issue ? 

Respectueusement,

- dev
